name: Audit

on:
  push:
    branches:
      - main

jobs:
  audit:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps: 
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v2

      - name: Verify deps
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Test
        run: go test -race -v -vet=off ./...